Fix(#46)
chafan-dev/chafan-frontend pull request #131
Opened 2021-03-26 10:05 UTC by AGDholo

## Related issues/discussions

#46 

## Description of the changes

Completely refactor the component to accommodate scaling.

* broken change
* new style

2021-03-26 10:10 UTC, AGDholo commented
https://github.com/chafan-dev/chafan-frontend/pull/131/commits/2022721d2c87f893b6916789799223ad5912ea55

2021-03-26 18:21 UTC, izgzhen commented
![Screen Shot 2021-03-26 at 11 20 50](https://user-images.githubusercontent.com/7168454/112676184-5b33fd00-8e25-11eb-854b-67232fe8dd77.png)

```
![](https://picsum.photos/2000/3000)
```

会产生白色的 v-sheet 背景？

2021-03-26 18:22 UTC, izgzhen requested changes
如果能把额外的白色背景变透明就好了

2021-03-27 02:17 UTC, AGDholo commented
![1SQod6WKEF](https://user-images.githubusercontent.com/13300332/112707355-add4ee00-8ee5-11eb-8b2b-a30f150f08b2.gif)

2021-03-27 02:25 UTC, AGDholo commented
兼容性测试：

* 未对一个答案中存在多张图片的情况下进行测试
* 未对一个问题中多个答案存在多张图片的情况下进行测试

2021-03-27 07:12 UTC, izgzhen approved these changes

2021-03-27 07:14 UTC, AGDholo reviewed
https://chafan-frontend-p725ifou9-chafan.vercel.app/questions/3ffUnpqGB4VszLvXDbE9?title=%E6%B5%8B%E8%AF%95%E6%8F%90%E9%97%AE%E6%8F%90%E9%97%AE

click-outside 不起作用，vuetify 文档对这个指令有错误说明，不用 object 方式写入 handler 无法生效

2021-03-27 07:20 UTC, izgzhen commented
> https://chafan-frontend-p725ifou9-chafan.vercel.app/questions/3ffUnpqGB4VszLvXDbE9?title=%E6%B5%8B%E8%AF%95%E6%8F%90%E9%97%AE%E6%8F%90%E9%97%AE
> 
> click-outside 不起作用，vuetify 文档对这个指令有错误说明，不用 object 方式写入 handler 无法生效

现在好像是可以的？

2021-03-27 07:21 UTC, izgzhen commented
我改了一些代码

2021-03-27 07:21 UTC, izgzhen commented
我还在挣扎 rebase commits 中...

2021-03-27 07:22 UTC, AGDholo commented
> 现在好像是可以的？

点击图片外部无法取消遮罩区域

2021-03-27 07:27 UTC, izgzhen commented
我 rebase 的时候把你 commit 里和功能无关的 cleanup 去了，因为 rebase 实在是工作量过大

2021-03-27 07:28 UTC, izgzhen commented
正好我今天也改了不少 viewer 上的东西，就 conflict 比较严重

2021-03-27 07:28 UTC, AGDholo commented
可以直接回滚，然后重新手动添加 commit，改动很小的

2021-03-27 07:33 UTC, izgzhen commented
@AGDholo 我加了个 hack 解决关闭问题

2021-03-27 07:36 UTC, izgzhen commented
我会试着解决下多个图片的问题

2021-03-27 08:18 UTC, merged