Refator/redesign
chafan-dev/chafan-frontend pull request #218
Opened 2021-08-03 10:04 UTC by AGDholo

## Related issues/discussions

## Description of the changes

![image](https://user-images.githubusercontent.com/13300332/127997798-9032faa4-3398-4cb8-baff-5cbe5d4f8a58.png)

2021-08-07 22:44 UTC, izgzhen commented
刚看到，我今天晚一点看一下，多谢！！

2021-08-08 04:49 UTC, AGDholo commented
个人资料布局那里有点不协调，但是现在更改的内容有点多，可能 review 太麻烦了，就没改其他的

2021-08-09 00:51 UTC, izgzhen requested changes

2021-08-09 00:51 UTC, izgzhen commented on src/components/home/UserFeed.vue
> +    activityVerbActivity(value) {
我们把这两个 two filters 改成简单的 dictionary 然后把 `activityData.subjects` 去掉？（因为重复了）

2021-08-09 00:51 UTC, izgzhen commented on src/components/home/UserFeed.vue
> +      <div
赞！

2021-08-09 00:51 UTC, izgzhen commented on src/styles/app.scss
> -@import '~vuetify/src/styles/styles.sass';
我记得引用 `$font-size-root` 之类是需要 import 这些的

2021-08-09 00:51 UTC, izgzhen commented on src/styles/app.scss
> -  max-width: 40%;
为何修改此处？

搜索框的话需要兼顾 mobile 和 desktop 上的尺寸

2021-08-09 00:51 UTC, izgzhen commented on yarn.lock
> +  resolved "https://registry.nlark.com/vuetify/download/vuetify-2.5.8.tgz#a23e6a7e77b77de0744b53cf1e7c9d40efac0635"
可以 revert 掉 yarn.lock 的修改吗？我可以在我这里用 yarnpkg 更新一下

2021-08-09 00:52 UTC, izgzhen commented
> 个人资料布局那里有点不协调，但是现在更改的内容有点多，但是怕 review 太麻烦了，就没改其他的

多谢。的确更建议把改动拆小一点

2021-08-09 01:02 UTC, izgzhen commented
<img width="717" alt="Screen Shot 2021-08-08 at 18 01 41" src="https://user-images.githubusercontent.com/7168454/128651439-1f5be5ac-1f8d-4673-9d99-2ca00c554332.png">

另外 `SubmissionCard` 似乎还没有用上新样式

2021-08-09 01:04 UTC, izgzhen commented
<img width="423" alt="Screen Shot 2021-08-08 at 18 03 35" src="https://user-images.githubusercontent.com/7168454/128651496-5cff7d2a-8a9b-4641-bfa1-33c956228dd2.png">

另外加了浅蓝色背景后，默认的按钮颜色（浅灰色）会变得难以识别。

2021-08-09 01:06 UTC, izgzhen commented
<img width="1273" alt="Screen Shot 2021-08-08 at 18 06 24" src="https://user-images.githubusercontent.com/7168454/128651598-dea6dda5-8ab2-4ba4-9241-e7683c1ddbe8.png">

类似的还有一些其他的背景色协调问题

2021-08-09 01:20 UTC, izgzhen commented
延伸思考一下的话感觉这样的改动：

1. 直接上线可能会有很多没有测试到的问题
2. 全改完的话预计工程量比较大

我再思考能否加入一个简易的动态主题系统。

2021-08-10 02:13 UTC, AGDholo commented
@izgzhen 那先把这个 pr 关了吗？

2021-08-10 02:57 UTC, izgzhen commented
> @izgzhen 那先把这个 pr 关了吗？

先开着吧

2021-08-21 19:03 UTC, merged

2021-08-21 19:06 UTC, izgzhen commented
@AGDholo 我加了一个 theme flag，大部分的 change 都整合了，Main 那部分不太好弄我先 revert 了

2021-08-22 03:00 UTC, AGDholo commented
@izgzhen 麻烦你了，我这几天有点忙来不及写代码