draft(style): unified style
chafan-dev/chafan-frontend pull request #43
Opened 2021-03-09 16:33 UTC by AGDholo

## Related issues/discussions

#15 

## Description of the changes

### 欢迎组件文本对齐：
![image](https://user-images.githubusercontent.com/13300332/110504462-27c05580-8138-11eb-9d90-3264076d5567.png)
------
### 取消分享卡片阴影：
![image](https://user-images.githubusercontent.com/13300332/110508219-bf737300-813b-11eb-9b16-fac3a31192ab.png)

### 问题预览卡片对齐：
![image](https://user-images.githubusercontent.com/13300332/110509559-30fff100-813d-11eb-882e-f49d739070f4.png)

2021-03-09 18:32 UTC, izgzhen requested changes

2021-03-09 18:34 UTC, izgzhen commented
![Screen Shot 2021-03-09 at 10 33 19 AM](https://user-images.githubusercontent.com/7168454/110520097-e6da2980-80c2-11eb-922c-08b1667c4fe5.png)

内嵌卡片是要加 outline？如果要加的话需要统一处理

2021-03-09 18:35 UTC, izgzhen commented
注意 Home.vue 里的“卡片”嵌套比较复杂，一条评论动态有两层嵌套：

```
Activity card {
  Comment card {
    Commented item card {
       ..
    }
  }
}
```

2021-03-09 18:39 UTC, izgzhen commented
Side note: 尽量把 PR 变小，多开几个，因为我也在改前端，一个 PR 里装太多不好 review，时间久了容易积累很多 conflict

2021-03-10 03:22 UTC, AGDholo commented
> 内嵌卡片是要加 outline？如果要加的话需要统一处理

想法是把所有内嵌的都取消阴影换成边框强调，用多个阴影的话不太好看而且容易造成阅读障碍

2021-03-10 03:24 UTC, izgzhen commented
> > 内嵌卡片是要加 outline？如果要加的话需要统一处理
> 
> 想法是把所有内嵌的都取消阴影换成边框强调，用多个阴影的话不太好看而且容易造成阅读障碍

嗯，embedded 不应该有阴影。这里的问题是选择加边框还是无边框。目前的实现是无边框，因为目前最多套两层，好像无边框也能看明白

2021-03-11 03:39 UTC, AGDholo commented
我把这个 pr draft 关了，后面用小 pr 的方式请求合并

2021-03-11 03:39 UTC, closed without merging

2021-03-11 04:39 UTC, izgzhen commented
好，麻烦啦！