refactor(UserWelcome): separate the independent welcome components
chafan-dev/chafan-frontend pull request #97
Opened 2021-03-14 10:46 UTC by AGDholo

## Description of the changes

- new design
- use base-card
- separate component
- logout user cannot found feed-bar

![image](https://user-images.githubusercontent.com/13300332/111065524-353d5d00-84f5-11eb-9cae-20aaa96b2f10.png)

![image](https://user-images.githubusercontent.com/13300332/111065594-86e5e780-84f5-11eb-8717-0f85fb3a44e4.png)

2021-03-14 19:11 UTC, izgzhen requested changes

2021-03-14 19:11 UTC, izgzhen commented on src/components/user/UserWelcome.vue
> +  @Emit('on-close-explore-sites')
In the onclick we already used the barebone `$emit` -- this decorated method is not necessary

2021-03-14 19:20 UTC, izgzhen commented on src/components/user/UserWelcome.vue
> +        <v-stepper class="elevation-0" value="1" vertical>
好像没有 step 到 2 的流程（如果只是显示有两步但是没有转换的话可能比较 confusing）？

我考虑有几个方案：

1. 可以把  `<router-link class="text-decoration-none" to="/profile/edit">` 变成一个打开新标签页，然后加一个 click handler，点完之后就到下一步，用户可以自己在新标签页填写个人资料
2. 把 profile edit 里面的表单部分 refactor 出来，嵌入到这个页面里。

2021-03-14 19:27 UTC, AGDholo commented on src/components/user/UserWelcome.vue
> +        <v-stepper class="elevation-0" value="1" vertical>
第一个方案不错

2021-03-14 19:32 UTC, izgzhen commented on src/components/user/UserWelcome.vue
> +        <v-stepper class="elevation-0" value="1" vertical>
> 第一个方案不错，click handle 是在哪里实现？

细节我还没想清楚，不过目前知道 js 里直接 window.open 是不行的。。

> 其实也可以点了链接直接显示到第二步，也不用去检测到底有没有改资料

是的

2021-03-14 19:33 UTC, izgzhen commented on src/components/user/UserWelcome.vue
> +        <v-stepper class="elevation-0" value="1" vertical>
理论上最好的实现方法应该是用 vuex 来追踪 pwa 上用户交互的状态，同时 persist 到数据库，不过感觉目前来说这个太复杂。

2021-03-14 19:35 UTC, izgzhen commented on src/components/user/UserWelcome.vue
> +        <v-stepper class="elevation-0" value="1" vertical>
如果用新标签页可能就不能用 `router-link` 只能用 `a` 了？router 导航支持 `target="_blank"`吗？

click handler 可以直接在链接上加一个 `@click="step = 2"`？

2021-03-14 19:36 UTC, AGDholo commented on src/components/user/UserWelcome.vue
> +        <v-stepper class="elevation-0" value="1" vertical>
支持，可以直接加

2021-03-15 04:19 UTC, AGDholo commented
![pZPyxuRVZi](https://user-images.githubusercontent.com/13300332/111103141-babe1d00-8588-11eb-9d59-b6f409fec0d0.gif)

2021-03-15 04:54 UTC, izgzhen approved these changes
LGTM, thanks!

2021-03-15 04:59 UTC, merged